### ISSUE TITLE
"RNCCheckbox" was not found in the UIManager

### ISSUE THREAD

**Issue by TiagoAndreAlmeida** [azeezat/react-native-select#1]
### when click to list dropdown itens the error show. 
tested on IOS

![Simulator Screen Shot - iPhone 8 Plus - 2023-01-04 at 11 24 08](https://user-images.githubusercontent.com/16297644/210576355-c2fafc3f-89a4-4f65-bde0-3d903adceeed.png)

**Comment by azeezat** [comment]
@TiagoAndreAlmeida can you give some more context on this issue using the bug report template. This would help in resolving the above issue. Thanks

**Comment by ligopsychakis-michalis** [comment]
@TiagoAndreAlmeida  I had the same issue. I fixed it with [this](https://github.com/react-native-checkbox/react-native-checkbox/issues/131#issuecomment-880162968). 
Hope it helps :)
