### ISSUE TITLE
Feature Request: Callback for Search Input in Dropdown

### ISSUE THREAD

**Issue by GabriPires** [azeezat/react-native-select#100]
Hi,

I’d like to request (or confirm if it already exists) the ability to receive the typed value from the search input of the Dropdown component through a callback. This would be incredibly useful for scenarios where I need to fetch data from an API to update the list dynamically based on the user’s search query.

For example, when dealing with large datasets (e.g., 20k+ results), it’s not feasible to load everything at once, and having such a callback would help optimize performance and user experience.

Does this functionality already exist, or is it something being planned for a future release?

Thank you for considering this suggestion!

**Comment by azeezat** [comment]
@GabriPires Yes, it does exist. use 

```js
searchControls={{searchCallback: value => function(value)}}
```

**Comment by azeezat** [comment]
The last example in the [sandbox](https://azeezat.github.io/react-native-select/) should explain it better
