### ISSUE TITLE
(Question) How to remove/decrease vertical padding on dropdown?

### ISSUE THREAD

**Issue by esorinas** [azeezat/react-native-select#22]
Hello! First of all, thanks for the job! I am just starting to program in react native and this component is useful and easy to use! :)

I am currently just trying to make a multi-select simple dropdown, and to fit my design I am trying to reduce the vertical padding of the dropdown box (the one containing first the placeholder and later on the selected items).

In particular, I want to remove/decrease the padding highlighted in the following image: 
![image](https://github.com/azeezat/react-native-select/assets/43247096/8bcd3436-02d6-4b1c-b5df-d65768012582)

I have read all the style props that you provide but I can not figure out which is the one that will serve this purpose. At first I thought `dropdownStyle` was the appropriate one. However, setting `paddingVertical` on `dropdownStyle` does not seem to alter the output. On the other hand, setting `paddingHorizontal` **does** change the layout as expected. 

My component usage is something like the following:
```
<Dropdown
    placeholder="Select stuff..."
    options={myData}
    value={selected}
    onValueChange={setSelected}
    isMultiple
    dropdownStyle={{
        paddingHorizontal: 10, // This works
        paddingVertical: 10, // This doesn't
    }}
/>
```
I have also tried to set `paddingVertical` on several other style properties, without success. May it be that this style is not changeable? Could you help me out with this? Thank you very much!

**Comment by azeezat** [comment]
@esorinas I'm glad this component has been helpful. The `minHeight` set on the component is preventing you from doing this. You can override it as follows. There is an example in the [sandbox](https://azeezat.github.io/react-native-select/)

```js 
      dropdownStyle={{
      paddingVertical: 5,
      paddingHorizontal: 5,
      minHeight: 40,
    }}
    dropdownIconStyle={{ top: 15, right: 10 }}
```

Thanks for reporting this issue. I hope this helps.

**Comment by esorinas** [comment]
@azeezat that was indeed helpful! The layout changes that I intended are now working. 

Thank you for the work and for the quick & useful answer! :)
