### ISSUE TITLE
'Select all' and 'Clear all' change text

### ISSUE THREAD

**Issue by hchrzaniuk** [azeezat/react-native-select#32]
**Is your feature request related to a problem? Please describe.**
The component cannot be customized to different languages.

**Describe the solution you'd like**
Could be a property to set tuple of texts.

**Describe alternatives you've considered**
Hope that everyone knows English... changing component. 

**Additional context**
n/a

**Comment by azeezat** [comment]
@hchrzaniuk Thanks for reporting this issue. A new version 1.1.4 has just been published  🚀.

Please add the following properties to your component

```js
selectAllControls={{
  selectAllText: 'Choose everything',
  unselectAllText: 'Remove everything',
  selectAllCallback: () => Alert.alert('You selected everything'),
  unselectAllCallback: () => Alert.alert('You removed everything'),
}}
```
You can also visit the [Sandbox](https://azeezat.github.io/react-native-select/) for examples.
Let me know if this helps.

**Comment by hchrzaniuk** [comment]
Perfect! Thank you!
