### ISSUE TITLE
Can we remove the 'select all' option from the list when isMultiple is set to true? I don't want the 'select all' option in my project.

### ISSUE THREAD

**Issue by ashish11sahu** [azeezat/react-native-select#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by azeezat** [comment]
@ashish11sahu Thanks for reporting this issue. A new version has now been published to address your concern.

By adding the properties below, the issue should be resolved.

```js
listControls={{
              hideSelectAll: true,
            }}
 ```
