### ISSUE TITLE
Option to limit selection or allow developer to manage value state.

### ISSUE THREAD

**Issue by webdobe** [azeezat/react-native-select#55]
**Is your feature request related to a problem? Please describe.**
I would like to limit the number of items available to be selected.

**Describe the solution you'd like**
Either state is managed or it isn't or have an option to limit the amount of selectable items.

**Describe alternatives you've considered**
If I set "selectedValue" I would expect the menu to use my state.  It currently has it's own state.

**Additional context**

**Comment by azeezat** [comment]
@webdobe a new prop `maxSelectableItems` now exists in the latest version.
