### ISSUE TITLE
Dropdown input has a non-editable bottom margin

### ISSUE THREAD

**Issue by JCcastagne** [azeezat/react-native-select#56]
**Describe the bug**
The default Dropdown component has margin at the bottom of the root component. There is a specific way I'm trying to style my screen and having the permanent margin at the bottom on it ruins intuitiveness.

**To Reproduce**
Placing the default Dropdown component on a screen.

**Expected behavior**

In this part of the code: 

_node_modules > react-native-input-select > src > components > Dropdown > Dropdown.tsx_
_line 75:_ `dropdownInputContainer: { marginBottom: 23, width: '100%' }`

Should be:
_line 75:_ `dropdownInputContainer: { marginBottom: 0, width: '100%' }`
or have a property that allows the dev to override the value (such as having a prop like ex: "dropdownInputBoxStyle")

**Smartphone (please complete the following information):**
 - OS: iOS, Android; all devices/platforms/OS
 - Version: 1.3.3

**Comment by azeezat** [comment]
@JCcastagne have you tried `dropdownContainerStyle={{ marginBottom: 0 }}`
`
