### ISSUE TITLE
scrollToIndex out of range: requested index 208 is out of 0 to 28

### ISSUE THREAD

**Issue by brvhprince** [azeezat/react-native-select#57]
**Describe the bug**
Crashes after a second search on a searchable multi-select modal.

**To Reproduce**
1. Create a multi-searchable select option
2. Search for a single item and select
3. Close the modal.
4. Open and search for another item in the list. Error occurs

**Expected behavior**
Subsequent search should work fine and show found items based on input or no available options if none.

**Screenshots**
![Screenshot - j - 2023-12-22 at 09 02 30](https://github.com/azeezat/react-native-select/assets/38820504/3bcaca5b-ab88-4668-aa10-6a88b646e841)

https://github.com/azeezat/react-native-select/assets/38820504/db1a8707-db1b-49a7-ac69-e0b740ac394d

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro max and Xiaomi Redmi Note 10 5G
 - OS: iOS and Android
 - OS Version: iOS version 17.0.1 and Android Version 13
 - Library Version: 1.3.2

**Comment by azeezat** [comment]
Please include the value you passed into your options array.

**Comment by azeezat** [comment]
#49
