### ISSUE TITLE
Custom render label/value for options 

### ISSUE THREAD

**Issue by brianbolnick** [azeezat/react-native-select#73]
**Is your feature request related to a problem? Please describe.**
We have many needs for our options to render rich content (sub text, custom icons or components, etc). As of now, it looks like this library only supports a string for the `name` value of an option. it would be great if it either took a component as well, or if we could pass in more custom data to the option prop and then have a sort of `renderListItem` kinda thing. 

Examples:

<img width="476" alt="image" src="https://github.com/azeezat/react-native-select/assets/4327477/51cd4dab-fe3d-4598-9713-eaa01f7501e9">

<img width="573" alt="image" src="https://github.com/azeezat/react-native-select/assets/4327477/a5331cd7-5b8f-472d-a45f-3dac15004f97">

**Comment by azeezat** [comment]
@brianbolnick I have created a new release addressing this issue. All you need to do is to update the options array as shown below

```js
options={[
              {
                value: '01',
                labelComponent: (
                  <View
                    style={{
                      flexDirection: 'row',
                      justifyContent: 'center',
                      alignItems: 'center',
                    }}>
                    <Image
                      style={styles.avatarStyle}
                      source={{
                        uri: 'https://avatar.iran.liara.run/public/boy?username=Ash',
                      }}
                    />

                    <Text>John Doe</Text>
                  </View>
                ),
              },
              {
                value: '02',
                labelComponent: (
                  <View
                    style={{
                      flexDirection: 'row',
                      justifyContent: 'center',
                      alignItems: 'center',
                    }}>
                    <Image
                      style={styles.avatarStyle}
                      source={{
                        uri: 'https://avatar.iran.liara.run/username?username=Azeezat+Raheem',
                      }}
                    />

                    <Text>Ashley Washington</Text>
                  </View>
                ),
              },
            ]}
            optionLabel={'labelComponent'}
            optionValue={'value'}
```

**Comment by brianbolnick** [comment]
> @brianbolnick I have created a new release addressing this issue. All you need to do is to update the options array as shown below
> 
> ```js
> options={[
>               {
>                 value: '01',
>                 labelComponent: (
>                   <View
>                     style={{
>                       flexDirection: 'row',
>                       justifyContent: 'center',
>                       alignItems: 'center',
>                     }}>
>                     <Image
>                       style={styles.avatarStyle}
>                       source={{
>                         uri: 'https://avatar.iran.liara.run/public/boy?username=Ash',
>                       }}
>                     />
> 
>                     <Text>John Doe</Text>
>                   </View>
>                 ),
>               },
>               {
>                 value: '02',
>                 labelComponent: (
>                   <View
>                     style={{
>                       flexDirection: 'row',
>                       justifyContent: 'center',
>                       alignItems: 'center',
>                     }}>
>                     <Image
>                       style={styles.avatarStyle}
>                       source={{
>                         uri: 'https://avatar.iran.liara.run/username?username=Azeezat+Raheem',
>                       }}
>                     />
> 
>                     <Text>Ashley Washington</Text>
>                   </View>
>                 ),
>               },
>             ]}
>             optionLabel={'labelComponent'}
>             optionValue={'value'}
> ```

You Rock! thanks!
