### ISSUE TITLE
Change the label of the search field

### ISSUE THREAD

**Issue by npalbrecht** [azeezat/react-native-select#76]
Hi there,

Is it possible to change the placeHolder of the search field ? I would like to translate the "Search" text as it's already possible with the "select all", etc.

Thanks :)

**Comment by azeezat** [comment]
@npalbrecht yes, that is possible with the following props

```js
searchControls={{
              textInputProps: {
                placeholder: 'Search anything here',
                placeholderTextColor: 'white',
              },
            }}
   ```

**Comment by azeezat** [comment]
searchControls={{
              textInputProps: {
                placeholder: 'Search anything here',
                placeholderTextColor: 'white',
              },
            }}
