### ISSUE TITLE
Typescript error with default import

### ISSUE THREAD

**Issue by trongbinh15** [azeezat/react-native-select#83]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I use default import same as docs
`import Dropdown from "react-native-input-select"`
The error happen when typescript do type-checking

**Screenshots**
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/b4c63394-030b-4a30-a6ab-1f69b3706c24">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I use expo.
I think the issue came from `package.json`, when I change `types` option to `  "types": "lib/typescript/src/index.d.ts"` the error is gone

**Comment by azeezat** [comment]
@trongbinh15 Thanks for reporting this issue. A new version has been published!
