### ISSUE TITLE
Having a data of 0 causing the placeholder to stay on

### ISSUE THREAD

**Issue by eroomeoj94** [azeezat/react-native-select#87]
**Describe the bug**
Having a data of 0 causing the placeholder to stay on. Using version 1.3.18

**Expected behavior**
The placeholder should be hidden

**Screenshots**
<img width="187" alt="Screenshot 2024-09-09 at 16 06 55" src="https://github.com/user-attachments/assets/7662da6c-a1ea-43e7-815c-8a894f7aead7">

**Smartphone**
 - Device: Android
 - OS: API 34

**Comment by kofiarkoh** [comment]
let me see if i can reproduce this issue since

**Comment by kofiarkoh** [comment]
@eroomeoj94  could you provide more reproducible steps. a code snippet of your usage would be very much appreciated

**Comment by eroomeoj94** [comment]
`<DropdownSelect
                            options={minutes}
                            key={'minute-select'}
                            placeholder={'Minutes'}
                            isSearchable={false}
                            dropdownContainerStyle={{width: 120}}
                            dropdownStyle={{
                                borderRadius: 30,
                                height: 40,
                                borderColor: Color.blue,
                                borderWidth: 3,
                                paddingVertical: 5,
                                paddingHorizontal: 15,
                                minHeight: 40,
                                width: 120,
                            }}
                            selectedItemStyle={{
                                fontFamily: StyleValues.regularFont,
                                fontSize: 16,
                            }}
                            selectedValue={durationData.minute}
                            dropdownIconStyle={{top: 15, right: 10}}
                            isMultiple={false}
                            onValueChange={setMinute}
                            primaryColor={Color.textBlue}/>`

`    const [minutes, setMinutes] = useState<any[]>([]);
    const [durationData, setDurationData] = useState<DurationData>(new DurationData());
        setMinutes(generateMinutesArray());
   function generateMinutesArray() {
        let minutes = [];
        for (let i = 0; i < 60; i += 5) {
            minutes.push({label: i.toString(), value: i});
        }
        return minutes;
    }
`

@kofiarkoh Please see above the snippets of code I've used
