### ISSUE TITLE
<Dropdown> (and especially Checkbox) crashes if using a numerical 0, in one of the options' labels.

### ISSUE THREAD

**Issue by monkeydioude** [azeezat/react-native-select#90]
**Describe the bug**
Version "1.3.18". To use the `options` props, we must pass an object with 2 keys, acting as `label` and `value`. In case one uses a numerical zero, we happen to witness a crash.

**To Reproduce**
```typescript
<Dropdown
    options={[{ label: 0, value: "numerical_0" }, { label: 1, value: "numerical_one" }]}
    optionLabel="label"
    optionValue="value"
    selectedValue={0}
    onValueChange={onValueChange}
/>
```

**Expected behavior**
The modal to appear, and displays correctly the "0" checkbox

**Screenshots**
This condition in `src/components/CheckBox/index.tsx` won't pass:

![image](https://github.com/user-attachments/assets/68e545c8-ed07-4e53-a9cc-9a01013cfa86)

**Additional context**
Ensute that `label` is a string fixes this.

**Comment by monkeydioude** [comment]
Sorry, I wish I could have ran tests afterwards, and also add tests for this case, but I cloned the project, ran `npm i` and got a lot of package version incompatibilities... That got me discouraged. I am sorry

**Comment by azeezat** [comment]
@monkeydioude  I'm glad to hear you found this component useful! The CONTRIBUTING.md file explains how to setup the project. I will take look at your PR. Thanks again for your feedback and contribution.

**Comment by kofiarkoh** [comment]
so i was able to reproduce the issue, we can go ahead and look at the PR #91

**Comment by azeezat** [comment]
@kofiarkoh @monkeydioude Did you use the latest version 2.0.0? I can't seem to be able to reproduce the error using that version.

**Comment by kofiarkoh** [comment]
@azeezat , could you try this?

```
 <DropdownSelect
            label="Border has been removed"
            placeholder="Select user"
            options={[
              {label: 0, value: '12'},
              {label: 9, value: '13'},
            ]}
            selectedValue={user}
            onValueChange={(itemValue: any) => setUser(itemValue)}
            isSearchable
            primaryColor={'purple'}
            dropdownStyle={{
              borderWidth: 0, // To remove border, set borderWidth to 0
            }}
            dropdownIcon={
              user && (
                <View style={styles.outerCircle}>
                  <View style={styles.innerCircle} />
                </View>
              )
            }
            dropdownIconStyle={user ? {top: 20, right: 15} : {}}
            searchControls={{
              textInputStyle: {
                color: 'blue',
                fontWeight: '500',
                minHeight: 10,
                paddingVertical: 10,
                paddingHorizontal: 5,
                width: '70%',
                textAlign: 'center',
                backgroundColor: 'pink',
              },
              textInputContainerStyle: {
                flex: 1,
                justifyContent: 'center',
                alignItems: 'center',
              },
              textInputProps: {
                placeholder: 'Search anything here',
                placeholderTextColor: 'white',
              },
            }}
          />
          ```

**Comment by azeezat** [comment]
@kofiarkoh Thanks, I can reproduce it now. I just merged the fix.
